#!/bin/bash

# To run this script, do 
# qsub -t 1-N submit_AmpliconClassifier.sh FILES
# FILES contains full paths to cycles and graph files
### Updated from 0.4.2 version (circa Jan 2021) to 0.4.10 (July 2022) and re-run:

#
#$ -N AA2AC
#$ -j y
#$ -S /bin/bash
#$ -cwd
#$ -l h_vmem=8G
#$ -pe sharedmem 8
#$ -l h_rt=10:00:00

unset MODULEPATH
. /etc/profile.d/modules.sh

CYCLE_GRAPH_FILE=$1

CYCLE=`head -n $SGE_TASK_ID $CYCLE_GRAPH_FILE | cut -f 2 | tail -n 1`
GRAPH=`head -n $SGE_TASK_ID $CYCLE_GRAPH_FILE | cut -f 3 | tail -n 1`
STAGE=`head -n $SGE_TASK_ID $CYCLE_GRAPH_FILE | cut -f 4 | tail -n 1`

### Based on https://github.com/jluebeck/AmpliconClassifier

export PATH=/exports/igmm/eddie/Glioblastoma-WGS/anaconda/envs/AA/bin:$PATH
export AA_DATA_REPO=/exports/igmm/eddie/Glioblastoma-WGS/scripts/AmpliconArchitect/data_repo

AC=/exports/igmm/eddie/Glioblastoma-WGS/scripts/AmpliconClassifier/amplicon_classifier.py
AA_CLASSIFIER_DIR=/exports/igmm/eddie/Glioblastoma-WGS/WGS/variants/ecdna/AA_classifier/AC_v0.4.10/${STAGE}

cd $AA_CLASSIFIER_DIR

### Classify amplicons generated by AA into either cyclic, non-cyclic (heavily rearranged) or BFB.
echo "Classifying amplicons using 0.4.10 version..."
python $AC \
    --ref GRCh38 \
    --cycles $CYCLE \
    --graph $GRAPH \
    --report_complexity --annotate_cycles_file \
    > classifier_stdout.log
    
    
    
    
    
    
